bank_P        = "..\\..\\DB\\bank.json"
election_P    = "..\\..\\DB\\election_sign_up.json"
lists_P       = "..\\..\\DB\\lists.json"
points_P      = "..\\..\\DB\\points.json"
shop_P        = "..\\..\\DB\\shop.json"
time_event_P  = "..\\..\\DB\\time_event.json"
